all: santa pzm

pzm: pzm.c
	gcc pzm.c -o pzm -lpthread
	@echo run as ./pzm -m M -s S -d D -z Z -c C -b B -u U -e E -h H -r R -n N 

santa: santa.c
	gcc santa.c -o santa -lpthread
	@echo run as ./santa -n numOfElves 
